export default function studentData (){
    return[
        {
            id:1,
            firstName:"Piotr",
            lastName:"Winston",
            email:"pwinston0@printfriendly.com",
            gender:"Male"
        },
        {
            id:2,
            firstName:"Demetris",
            lastName:"Lardnar",
            email:"dlardnar1@woothemes.com",
            gender:"Male"
        },
        {
            id:3,
            firstName:"Lanie",
            lastName:"Meiklam",
            email:"lmeiklam2@uol.com.br",
            gender:"Male"
        },
        {
            id:4,
            firstName:"Cece",
            lastName:"Thorrold",
            email:"cthorrold3@state.tx.us",
            gender:"Male"
        },
        {
            id:5,
            firstName:"Renard",
            lastName:"Crowcroft",
            email:"rcrowcroft4@blogspot.com",
            gender:"Male"
        },
        {
            id:6,
            firstName:"Augustin",
            lastName:"Di Maria",
            email:"adimaria5@shutterfly.com",
            gender:"Genderfluid"
        },
        {
            id:7,
            firstName:"Damian",
            lastName:"Yashnov",
            email:"dyashnov6@purevolume.com",
            gender:"Non-binary"
        },
        {
            id:8,
            firstName:"Arte",
            lastName:"Lafayette",
            email:"alafayette7@wordpress.com",
            gender:"Genderfluid"
        },
        {
            id:9,
            firstName:"Sindee",
            lastName:"Jakoviljevic",
            email:"sjakoviljevic8@sourceforge.net",
            gender:"Female"
        },
        {
            id:10,
            firstName:"Con",
            lastName:"Batchan",
            email:"cbatchan9@google.co.uk",
            gender:"Female"},
        ];
        }
  